version: "3"
services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app/sample-project
      - /usr/app/sample-project/node_modules
    environment:
      NODE_ENV: development
    command:
      npm run dev