version: "3"
services:
  dev:
    build:
      context: .
      dockerfile: ./dockerfile
      args:
        - APP_ENV=development
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app/sample-project
      - /usr/app/sample-project/node_modules
    command:
      npm run dev
  production:
    build:
      context: .
      dockerfile: ./dockerfile
      args:
        - APP_ENV=production
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app/sample-project
      - /usr/app/sample-project/node_modules
    command:
      npm run start