const path = require('path');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');

// move all css file into bundle instead using inline style
const extractSass = new ExtractTextPlugin({
	filename: '[name].css',
	disable: process.env.NODE_ENV === 'development'
});

module.exports = {
	context: path.resolve(process.cwd(), 'src'),
	entry: {
		vendor: ['react', 'jquery']
	},
	output: {
		path: path.resolve(process.cwd(), 'dist'),
		filename: '[name].bundle.js',
		publicPath: '/dist/'
	},
	module: {
		rules: [
			{
				enforce: 'pre',
				test: /\.(jsx|js)$/,
				include: path.resolve(process.cwd(), 'src'),
				loader: 'eslint-loader'
			},
			{
				test: /\.(jsx|js)$/,
				include: path.resolve(process.cwd(), 'src'),
				use: [
					{
						loader: 'babel-loader',
						options: {
							cacheDirectory: true
						}
					}
				]
			},
			{
				test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
				use: {
					loader: 'url-loader',
					options: {
						limit: 10000
					}
				}
			},
			{
				test: /\.scss$/,
				use: extractSass.extract({
					use: [
						{
							loader: 'css-loader',
							options: {
								sourceMap: true,
								modules: true,
								localIdentName: '[path]___[name]__[local]___[hash:base64:5]'
							}
						}, // collect css files and move it into a string
						{ loader: 'resolve-url-loader' }, // resolve url when using image paths
						{ loader: 'sass-loader', options: { sourceMap: true } } // compile scss to css
					],
					fallback: 'style-loader' // get string generated by css-loader and put it into <style />
				})
			},
			{
				test: /\.css$/,
				use: extractSass.extract({
					use: [
						{
							loader: 'css-loader',
							options: {
								sourceMap: true,
								modules: true,
								localIndentName: '[name]__[local]___[hash:base64:5]' 
							}
						}
					],
					fallback: 'style-loader'
				})
			},
			{
				test: /\.less$/,
				use: [
					'style-loader',
					{ loader: 'css-loader', options: { sourceMap: 1 } },
					'postcss-loader', 'less-loader'
				]
			}
		]
	},
	resolve: {
		extensions: ['.', '.js', '.jsx'],
		alias: { // use object type for alias
			public: path.resolve(__dirname, 'public')
		},
		modules: [ // use array type for modules
			'node_modules',
			path.resolve('./src')
		]
	},
	plugins: [
		new webpack.optimize.CommonsChunkPlugin({
			name: 'commons',
			filename: 'commons.js'
		}),
		new webpack.ProvidePlugin({
			$: 'jquery',
			jQuery: 'jquery'
		}),
		new HtmlWebpackPlugin({
			filename: 'index.html',
			template: path.resolve(process.cwd(), 'view/index.html')
		}),
		extractSass
	]
};
