version: 2
jobs:
  build1:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Echo
          command: echo "Hello World"
  build2:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Echo Test
          command: echo "Hello guys"
workflows:
  version: 2
  build1_and_build2:
    jobs:
      - build1
      - build2:
          requires:
            - build1