version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Echo
          command: echo "Hello World"
  build2:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Echo Test
          command: echo "Hello guys"